### ISSUE TITLE
Experiment checklist

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/polyphemus#14]
- [ ] Run experiment without `s_axilite` interface for arrays.
- [ ] Run experiment with `s_axilite` interface for arrays but no `m_axi` interface.
- [ ] Run the partition experiments (manual and partition) and see if there is difference in resource usage.
